import Sidebar from '../components/Sidebar';
import constants from "../constants";

// RBAC Manager class
class RbacManager {
  constructor(role, form, inWF = null, isOwner = false) {
    this.currentRole = role;
    this.currentForm = form;
    this.itemInWF = inWF;
    this.isUserOwner = isOwner;
  }
  //

  static roleformfieldmap = {
    [constants.ROLES.SUPER_ADMIN]: {
      orderList: {
        fields: {
          ordersContent: { visible: true, editable: true },
          approvalButton: { visible: true, editable: true },
          addButton: { visible: true, editable: true },
          actionMenu: { visible: true, editable: true },
          ordersTable: { visible: true, editable: true },
          ordersPagination: { visible: true, editable: true },
          orderNumber: { visible: true, editable: true },
          companyName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          expectedDeliveryDate: { visible: true, editable: true },
          paymentStatus: { visible: true, editable: true },
          toyalAmount: { visible: true, editable: true },
          paidAmount: { visible: true, editable: true },
          status: { visible: true, editable: true },
          action: { visible: true, editable: true },
          orderBy: { visible: true, editable: true },
        },
      },
      orderDetailAdd: {
        fields: {
          orderDetails: { visible: true, editable: false },
          customerName: { visible: true, editable: false },
          branchName: { visible: true, editable: false },
          orderBy: { visible: true, editable: false },
          erpId: { visible: true, editable: false },
          entity: { visible: true, editable: false },
          paymentMethod: { visible: true, editable: false },
          totalAmount: { visible: true, editable: false },
          paidAmount: { visible: true, editable: false },
          deliveryCharges: { visible: true, editable: false },
          expectedDeliveryDate: { visible: true, editable: false },
          pricingPolicy: { visible: true, editable: false },
          createdDate: { visible: false, editable: false },
          updatedDate: { visible: false, editable: false },
          driver: { visible: true, editable: false },
          vehicleNumber: { visible: true, editable: false },
          images: { visible: true, editable: true },
          addImages: { visible: false, editable: false },
          products: { visible: false, editable: false },
          productIdCol: { visible: true, editable: false },
          quantityCol: { visible: true, editable: false },
          unitCol: { visible: true, editable: false },
          unitPriceCol: { visible: true, editable: false },
          sugarTaxPriceCol: { visible: true, editable: false },
          vatPercentageCol: { visible: true, editable: false },
          netAmountCol: { visible: true, editable: false },
          orderFooter: { visible: true, editable: false },
          stock: { visible: true, editable: false},
          btnSave: { visible: true, editable: false },
          btnCancel: { visible: true, editable: false },
          btnInvoice: { visible: true, editable: false },
          btnPay: { visible: false, editable: false },
          btnInventory: { visible: true, editable: false },
          actionButtons: { visible: true, editable: false },
          btnApprove: { visible: false, editable: false },
          btnReject: { visible: false, editable: false },
        }
      },
      orderDetailEdit: {
        fields: {
          orderDetails: { visible: true, editable: false },
          customerName: { visible: true, editable: false },
          branchName: { visible: true, editable: false },
          orderBy: { visible: true, editable: false },
          erpId: { visible: true, editable: false },
          entity: { visible: true, editable: false },
          paymentMethod: { visible: true, editable: false },
          totalAmount: { visible: true, editable: false },
          paidAmount: { visible: true, editable: false },
          deliveryCharges: { visible: true, editable: false },
          expectedDeliveryDate: { visible: true, editable: false },
          pricingPolicy: { visible: true, editable: true },
          createdDate: { visible: false, editable: false },
          updatedDate: { visible: false, editable: false },
          driver: { visible: false, editable: false },
          vehicleNumber: { visible: false, editable: false },
          images: { visible: false, editable: false },
          addImages: { visible: false, editable: false },
          products: { visible: false, editable: false },
          orderFooter: { visible: true, editable: false },
          stock: { visible: false, editable: false},
          btnSave: { visible: false, editable: false },
          btnCancel: { visible: true, editable: false },
          btnInvoice: { visible: false, editable: false },
          btnInventory: { visible: false, editable: false },
          actionButtons: { visible: false, editable: false },
          btnApprove: { visible: false, editable: false },
          btnReject: { visible: false, editable: false },
        }
      },
      catalog: {
        fields: {
          selectBranch: { visible: false, editable: false },
          search: { visible: true, editable: true },
          products: { visible: true, editable: true },
          quantityController: { visible: false, editable: false },
          addToCart: { visible: false, editable: false },
          goToCart: { visible: false, editable: false },
          sort: { visible: false, editable: false }
        }
      },
      customersList: {
        fields: {
          name: { visible: true, editable: true },
          contact: { visible: true, editable: true },
          email: { visible: true, editable: true },
          status: { visible: true, editable: true },
          location: { visible: true, editable: true },
        },
      },
      invitesList: {
        fields: {
          name: { visible: true, editable: true },
          email: { visible: true, editable: true },
          date: { visible: true, editable: true },
          status: { visible: true, editable: true },
          actions: { visible: true, editable: true },
        },
      },
      custBusDetailAdd: {
        fields: {
          companyName: { visible: true, editable: true },
          businessType: { visible: true, editable: true },
          address: { visible: true, editable: true },
          contact: { visible: true, editable: true },
          registrationNumber: { visible: true, editable: true },
        },
      },
      custBusDetailEdit: {
        fields: {
          companyName: { visible: true, editable: true },
          businessType: { visible: true, editable: true },
          address: { visible: true, editable: true },
          contact: { visible: true, editable: true },
          registrationNumber: { visible: true, editable: true },
        },
      },
      custFinInfoAdd: {
        fields: {
          bankName: { visible: true, editable: true },
          accountNumber: { visible: true, editable: true },
          creditLimit: { visible: true, editable: true },
          paymentTerms: { visible: true, editable: true },
          taxInfo: { visible: true, editable: true },
        },
      },
      custFinInfoEdit: {
        fields: {
          bankName: { visible: true, editable: true },
          accountNumber: { visible: true, editable: true },
          creditLimit: { visible: true, editable: true },
          paymentTerms: { visible: true, editable: true },
          taxInfo: { visible: true, editable: true },
        },
      },
      custDocsAdd: {
        fields: {
          documentType: { visible: true, editable: true },
          documentName: { visible: true, editable: true },
          uploadDate: { visible: true, editable: true },
          expiryDate: { visible: true, editable: true },
          status: { visible: true, editable: true },
        },
      },
      custDocsEdit: {
        fields: {
          documentType: { visible: true, editable: true },
          documentName: { visible: true, editable: true },
          uploadDate: { visible: true, editable: true },
          expiryDate: { visible: true, editable: true },
          status: { visible: true, editable: true },
        },
      },
      branchesAdd: {
        fields: {
          branchName: { visible: true, editable: true },
          location: { visible: true, editable: true },
          manager: { visible: true, editable: true },
          contact: { visible: true, editable: true },
          status: { visible: true, editable: true },
        },
      },
      branchesEdit: {
        fields: {
          branchName: { visible: true, editable: true },
          location: { visible: true, editable: true },
          manager: { visible: true, editable: true },
          contact: { visible: true, editable: true },
          status: { visible: true, editable: true },
        },
      },
      prodMoQAdd: {
        fields: {
          productName: { visible: true, editable: true },
          minQuantity: { visible: true, editable: true },
          priceBreaks: { visible: true, editable: true },
          effectiveDate: { visible: true, editable: true },
          notes: { visible: true, editable: true },
        },
      },
      prodMoQEdit: {
        fields: {
          productName: { visible: true, editable: true },
          minQuantity: { visible: true, editable: true },
          priceBreaks: { visible: true, editable: true },
          effectiveDate: { visible: true, editable: true },
          notes: { visible: true, editable: true },
        },
      },
      supList: {
        fields: {
          btnAdd: { visible: false, editable: false },
        },
      },
      supDetailAdd: {
        fields: {
          customerName: { visible: true, editable: false },
          branch: { visible: true, editable: false },
          issueType: { visible: true, editable: true },
          issueName: { visible: true, editable: true },
          issueDetails: { visible: true, editable: false },
          images: { visible: true, editable: true },
          issueStatus: { visible: true, editable: true },
          assignedTo: { visible: true, editable: true },
          btnSave: { visible: true, editable: true },
        },
      },
      supDetailEdit: {
        fields: {
          customerName: { visible: true, editable: false },
          branch: { visible: true, editable: false },
          issueType: { visible: true, editable: true },
          issueName: { visible: true, editable: false },
          issueDetails: { visible: true, editable: false },
          images: { visible: true, editable: true },
          issueStatus: { visible: true, editable: true },
          assignedTo: { visible: true, editable: true },
          btnSave: { visible: true, editable: true },
        },
      },
      maintList: {
        fields: {
          btnAdd: { visible: false, editable: false },
        },
      },
      maintDetailAdd: {
        fields: {
          customerName: { visible: true, editable: false },
          branch: { visible: true, editable: true },
          issueType: { visible: true, editable: true },
          issueName: { visible: true, editable: true },
          createdDate: { visible: false, editable: false },
          machineSerialNumber: { visible: true, editable: true },
          warrantyEndDate: { visible: true, editable: false },
          maintenanceCharges: { visible: false, editable: true },
          issueDetails: { visible: true, editable: true },
          btnAddvideos: { visible: true, editable: true },
          btnAddimages: { visible: true, editable: true },
          status: { visible: false, editable: true },
          assignedTo: { visible: true, editable: true },
        },
      },
      maintDetailEdit: {
        fields: {
          customerName: { visible: true, editable: false },
          branch: { visible: true, editable: false },
          issueType: { visible: true, editable: false },
          issueName: { visible: true, editable: false },
          createdDate: { visible: true, editable: false },
          machineSerialNumber: { visible: true, editable: false },
          warrantyEndDate: { visible: true, editable: false },
          maintenanceCharges: { visible: true, editable: true },
          issueDetails: { visible: true, editable: false },
          btnAddvideos: { visible: true, editable: false },
          btnAddimages: { visible: true, editable: false },
          status: { visible: true, editable: true },
          assignedTo: { visible: true, editable: true },
        },
      },
      prodDetail: {
        fields: {
          name: { visible: true, editable: true },
          description: { visible: true, editable: true },
          price: { visible: true, editable: true },
          stock: { visible: true, editable: true },
          specifications: { visible: true, editable: true },
        },
      },
      orderListing: {
        fields: {
          orderNumber: { visible: true, editable: true },
          status: { visible: true, editable: true },
          customer: { visible: true, editable: true },
          date: { visible: true, editable: true },
          amount: { visible: true, editable: true },
        },
      },
      checkoutPage: {
        fields: {
          customer: { visible: true, editable: true },
          shippingAddress: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          items: { visible: true, editable: true },
          discounts: { visible: true, editable: true },
        },
      },
      sidemenu: {
        fields: {
          orders: { visible: true, editable: true },
          customers: { visible: true, editable: true },
          products: { visible: true, editable: true },
          suppliers: { visible: true, editable: true },
          maintenance: { visible: true, editable: true },
          reports: { visible: true, editable: true },
          settings: { visible: true, editable: true },
        },
      },
      SidebarList: {
        fields: {
          Dashboard: {visible: false, editable: true},
          Company: {visible: false, editable: true},
          Settings: {visible: false, editable: true}
        }
      }

    },

    [constants.ROLES.CUSTOMER_PRIMARY]: {
      orderList: {
        fields: {
          orderNumber: { visible: true, editable: false },
          companyName: { visible: false, editable: true },
          branchName: { visible: true, editable: true },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          expectedDeliveryDate: { visible: true, editable: true },
          paymentStatus: { visible: true, editable: true },
          totalAmount: { visible: true, editable: true },
          paidAmount: { visible: true, editable: true },
          status: { visible: true, editable: true },
          action: { visible: true, editable: true },
          addButton: { visible: false, editable: false },
          approvalButton: { visible: false, editable: false },
          orderBy: { visible: true, editable: true },
        },
      },
      orderDetailAdd: {
        fields: {
          orderDetails: { visible: false, editable: false },
          customerName: { visible: false, editable: false },
          branchName: { visible: false, editable: false },
          orderBy: { visible: false, editable: false },
          erpId: { visible: false, editable: false },
          entity: { visible: false, editable: false },
          paymentMethod: { visible: false, editable: false },
          totalAmount: { visible: false, editable: false },
          paidAmount: { visible: false, editable: false },
          deliveryCharges: { visible: false, editable: false },
          expectedDeliveryDate: { visible: false, editable: false },
          pricingPolicy: { visible: false, editable: false },
          createdDate: { visible: false, editable: false },
          updatedDate: { visible: false, editable: false },
          driver: { visible: false, editable: false },
          vehicleNumber: { visible: false, editable: false },
          images: { visible: false, editable: false },
          addImages: { visible: false, editable: false },
          products: { visible: false, editable: false },
          productIdCol: { visible: false, editable: false },
          quantityCol: { visible: false, editable: false },
          unitCol: { visible: false, editable: false },
          unitPriceCol: { visible: false, editable: false },
          sugarTaxPriceCol: { visible: false, editable: false },
          vatPercentageCol: { visible: false, editable: false },
          netAmountCol: { visible: false, editable: false },
          orderFooter: { visible: false, editable: false },
          stock: { visible: false, editable: false },
          btnSave: { visible: false, editable: false },
          btnCancel: { visible: false, editable: false },
          btnInvoice: { visible: false, editable: false },
          btnInventory: { visible: false, editable: false },
          actionButtons: { visible: false, editable: false },
          btnApprove: { visible: false, editable: false },
          btnReject: { visible: false, editable: false },
        },
      },
      orderDetailEdit: {
        fields: {
          orderDetails: { visible: true, editable: false },
          customerName: { visible: true, editable: false },
          branchName: { visible: true, editable: false },
          orderBy: { visible: true, editable: false },
          erpId: { visible: true, editable: false },
          entity: { visible: true, editable: false },
          paymentMethod: { visible: true, editable: false },
          totalAmount: { visible: true, editable: false },
          paidAmount: { visible: true, editable: false },
          deliveryCharges: { visible: true, editable: false },
          expectedDeliveryDate: { visible: true, editable: false },
          pricingPolicy: { visible: false, editable: false },
          createdDate: { visible: false, editable: false },
          updatedDate: { visible: false, editable: false },
          driver: { visible: false, editable: false },
          vehicleNumber: { visible: false, editable: false },
          images: { visible: false, editable: false },
          addImages: { visible: false, editable: false },
          products: { visible: true, editable: false },
          productIdCol: { visible: true, editable: false },
          quantityCol: { visible: true, editable: false },
          unitCol: { visible: true, editable: false },
          unitPriceCol: { visible: true, editable: false },
          sugarTaxPriceCol: { visible: true, editable: false },
          vatPercentageCol: { visible: true, editable: false },
          netAmountCol: { visible: true, editable: false },
          orderFooter: { visible: true, editable: false },
          stock: { visible: false, editable: false },
          btnSave: { visible: false, editable: false },
          btnCancel: { visible: true, editable: true },
          btnInvoice: { visible: true, editable: true },
          btnPay: { visible: true, editable: true },
          btnInventory: { visible: false, editable: true },
          actionButtons: { visible: true, editable: false },
          btnApprove: { visible: false, editable: false },
          btnReject: { visible: false, editable: false },
        },
      },
      catalog: {
        fields: {
          selectBranch: { visible: true, editable: true },
          search: { visible: true, editable: true },
          products: { visible: true, editable: true },
          quantityController: { visible: true, editable: true },
          addToCart: { visible: true, editable: true },
          goToCart: { visible: true, editable: true },
          sort: { visible: true, editable: true }
        }
      },

      supList: {
        fields: {
          btnAdd: { visible: true, editable: false },
        },
      },
      supDetailAdd: {
        fields: {
          customerName: { visible: true, editable: false },
          branch: { visible: true, editable: true },
          issueType: { visible: true, editable: true },
          issueName: { visible: true, editable: true },
          issueDetails: { visible: true, editable: true },
          images: { visible: true, editable: true },
          issueStatus: { visible: true, editable: true },
          assignedTo: { visible: false, editable: true },
          btnSave: { visible: true, editable: true },
        },
      },
      supDetailEdit: {
        fields: {
          customerName: { visible: true, editable: false },
          branch: { visible: true, editable: true },
          issueType: { visible: true, editable: true },
          issueName: { visible: true, editable: false },
          issueDetails: { visible: true, editable: false },
          images: { visible: true, editable: true },
          issueStatus: { visible: true, editable: false },
          assignedTo: { visible: false, editable: true },
          btnSave: { visible: true, editable: true },
        },
      },
      custDetailsAdd: {
        fields: {
          companyNameEn: { visible: true, editable: true },
          companyNameLc: { visible: true, editable: true },
          crNumber: { visible: true, editable: true },
          vatRegistrationNumber: { visible: true, editable: true },
          baladeahLicense: { visible: true, editable: true },
          companyType: { visible: true, editable: true },
          businessType: { visible: true, editable: true },
          businessTypeOther: { visible: true, editable: true },
          assignedTo: { visible: false, editable: true },
          assignedToEntityWise: { visible: false, editable: true },
          interCompany: { visible: false, editable: false },
          entity: { visible: false, editable: true },
          deliveryLocations: { visible: true, editable: true },
          brandName: { visible: true, editable: true },
          brandNameArabic: { visible: true, editable: true },
          company_logo: { visible: true, editable: true },
          brand_logo: { visible: true, editable: true },
          primaryContactName: { visible: true, editable: true },
          primaryContactDesignation: { visible: true, editable: true },
          primaryContactEmail: { visible: true, editable: false },
          primaryContactMobile: { visible: true, editable: true },
          businessHeadSameAsPrimary: { visible: true, editable: true },
          businessHeadName: { visible: true, editable: true },
          businessHeadDesignation: { visible: true, editable: true },
          businessHeadEmail: { visible: true, editable: true },
          businessHeadMobile: { visible: true, editable: true },
          financeHeadName: { visible: true, editable: true },
          financeHeadDesignation: { visible: true, editable: true },
          financeHeadEmail: { visible: true, editable: true },
          financeHeadMobile: { visible: true, editable: true },
          purchasingHeadName: { visible: true, editable: true },
          purchasingHeadDesignation: { visible: true, editable: true },
          purchasingHeadEmail: { visible: true, editable: true },
          purchasingHeadMobile: { visible: true, editable: true },
          buildingName: { visible: true, editable: true },
          street: { visible: true, editable: true },
          district: { visible: true, editable: true },
          city: { visible: true, editable: true },
          region: { visible: true, editable: true },
          zone: { visible: true, editable: true },
          geolocation: { visible: true, editable: true },
          pincode: { visible: true, editable: true },
          dulySigned: { visible: true, editable: true },
          crCertificate: { visible: true, editable: true },
          vatCertificate: { visible: true, editable: true },
          nationalID: { visible: true, editable: true },
          bankLetter: { visible: true, editable: true },
          nonTradingDocuments: { visible: true, editable: true },
          bankName: { visible: true, editable: true },
          bankAccountNumber: { visible: true, editable: true },
          iban: { visible: true, editable: true },
          pricingPolicy: {visible: false, editable: true},
          prePayment: { visible: false, editable: true },
          partialPayment: { visible: false, editable: true },
          advancePayment: { visible: false, editable: true },
          COD: { visible: false, editable: true },
          credit: { visible: false, editable: true },
          creditLimit: { visible: false, editable: true },
          creditPeriod: { visible: false, editable: true },
          btnSave: { visible: true, editable: true },
          btnBlock: {visible: false, editable: true},
          btnUnblock: {visible: false, editable: true},
          customerSource: { visible: false, editable: true },
          deliveryCost: {visible: false, editable: true},
          
        }
      },
      custDetailsEdit: {
        fields: {
          companyNameEn: { visible: true, editable: true },
          companyNameLc: { visible: true, editable: true },
          crNumber: { visible: true, editable: true },
          vatRegistrationNumber: { visible: true, editable: true },
          baladeahLicense: { visible: true, editable: true },
          companyType: { visible: true, editable: true },
          businessType: { visible: true, editable: true },
          businessTypeOther: { visible: true, editable: true },
          interCompany: { visible: false, editable: true },
          entity: { visible: false, editable: true },
          deliveryLocations: { visible: true, editable: true },
          brandName: { visible: true, editable: true },
          brandNameArabic: { visible: true, editable: true },
          company_logo: { visible: true, editable: true },
          brand_logo: { visible: true, editable: true },
          primaryContactName: { visible: true, editable: false },
          primaryContactDesignation: { visible: true, editable: false },
          primaryContactEmail: { visible: true, editable: false },
          primaryContactMobile: { visible: true, editable: false },
          businessHeadSameAsPrimary: { visible: true, editable: true },
          businessHeadName: { visible: true, editable: true },
          businessHeadDesignation: { visible: true, editable: true },
          businessHeadEmail: { visible: true, editable: true },
          businessHeadMobile: { visible: true, editable: true },
          financeHeadName: { visible: true, editable: true },
          financeHeadDesignation: { visible: true, editable: true },
          financeHeadEmail: { visible: true, editable: true },
          financeHeadMobile: { visible: true, editable: true },
          purchasingHeadName: { visible: true, editable: true },
          purchasingHeadDesignation: { visible: true, editable: true },
          purchasingHeadEmail: { visible: true, editable: true },
          purchasingHeadMobile: { visible: true, editable: true },
          buildingName: { visible: true, editable: true },
          street: { visible: true, editable: true },
          district: { visible: true, editable: true },
          city: { visible: true, editable: true },
          region: { visible: true, editable: true },
          zone: { visible: true, editable: true },
          geolocation: { visible: true, editable: true },
          pincode: { visible: true, editable: true },
          dulySigned: { visible: true, editable: true },
          crCertificate: { visible: true, editable: true },
          vatCertificate: { visible: true, editable: true },
          nationalID: { visible: true, editable: true },
          bankLetter: { visible: true, editable: true },
          nonTradingDocuments: { visible: true, editable: true },
          bankName: { visible: true, editable: true },
          accountNumber: { visible: true, editable: true },
          ibanNumber: { visible: true, editable: true },
          prePayment: { visible: false, editable: true },
          partialPayment: { visible: false, editable: true },
          advancePayment: { visible: false, editable: true },
          COD: { visible: false, editable: true },
          credit: { visible: false, editable: true },
          creditLimit: { visible: false, editable: true },
          creditPeriod: { visible: false, editable: true },
          assignedTo: { visible: false, editable: true },
          assignedToEntityWise: { visible: false, editable: true },
          customerSource: { visible: false, editable: true },
          deliveryCost: { visible: false, editable: true },
        },
      },
      maintList: {
        fields: {
          btnAdd: { visible: false, editable: false },
        },
      },
      maintDetailAdd: {
        fields: {
          customerName: { visible: true, editable: false },
          branch: { visible: true, editable: true },
          issueType: { visible: true, editable: true },
          issueName: { visible: true, editable: true },
          createdDate: { visible: false, editable: false },
          machineSerialNumber: { visible: true, editable: true },
          warrantyEndDate: { visible: false, editable: false },
          maintenanceCharges: { visible: false, editable: false },
          issueDetails: { visible: true, editable: true },
          btnAddvideos: { visible: true, editable: true },
          btnAddimages: { visible: true, editable: true },
          status: { visible: false, editable: false },
          assignedTo: { visible: false, editable: false },
        },
      },
      maintDetailEdit: {
        fields: {
          customerName: { visible: true, editable: false },
          branch: { visible: true, editable: false },
          issueType: { visible: true, editable: false },
          issueName: { visible: true, editable: false },
          createdDate: { visible: true, editable: false },
          machineSerialNumber: { visible: true, editable: false },
          warrantyEndDate: { visible: true, editable: false },
          maintenanceCharges: { visible: true, editable: true },
          issueDetails: { visible: true, editable: false },
          btnAddvideos: { visible: true, editable: false },
          btnAddimages: { visible: true, editable: false },
          status: { visible: true, editable: true },
          assignedTo: { visible: true, editable: true },
        },
      },
      SidebarList: {
        fields: {
          Dashboard: {visible: false, editable: true},
          Customers: {visible: false, editable: true},
          Settings: {visible: false, editable: true}
        }
      }
    },

    [constants.ROLES.BRANCH_PRIMARY]: {
      orderList: {
        fields: {
          orderNumber: { visible: true, editable: true },
          companyName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          expectedDeliveryDate: { visible: true, editable: true },
          paymentStatus: { visible: true, editable: true },
          toyalAmount: { visible: true, editable: true },
          paidAmount: { visible: true, editable: true },
          status: { visible: true, editable: true },
          action: { visible: true, editable: true },
          addButton: { visible: true, editable: true },
          orderBy: { visible: true, editable: true },
        },
      },
      orderDetailAdd: {
        fields: {
          orderDetails: { visible: true, editable: false },
          customerName: { visible: false, editable: false },
          branchName: { visible: true, editable: false },
          orderBy: { visible: true, editable: false },
          erpId: { visible: true, editable: false },
          entity: { visible: true, editable: false },
          paymentMethod: { visible: true, editable: false },
          totalAmount: { visible: true, editable: false },
          paidAmount: { visible: false, editable: false },
          deliveryCharges: { visible: true, editable: false },
          expectedDeliveryDate: { visible: true, editable: true },
          pricingPolicy: { visible: false, editable: false },
          createdDate: { visible: false, editable: false },
          updatedDate: { visible: false, editable: false },
          driver: { visible: true, editable: false },
          vehicleNumber: { visible: true, editable: false },
          images: { visible: true, editable: false },
          addImages: { visible: false, editable: false },
          products: { visible: true, editable: false },
          orderFooter: { visible: true, editable: false },
          stock: { visible: false, editable: false },
          btnSave: { visible: true, editable: false },
          btnCancel: { visible: true, editable: false },
          btnInvoice: { visible: true, editable: false },
          btnInventory: { visible: true, editable: false },
          actionButtons: { visible: true, editable: false },
          btnApprove: { visible: false, editable: false },
          btnReject: { visible: false, editable: false },
        },
      },
      orderDetailEdit: {
        fields: {
          orderDetails: { visible: true, editable: false },
          customerName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          orderBy: { visible: true, editable: false },
          erpId: { visible: true, editable: false },
          entity: { visible: true, editable: false },
          paymentMethod: { visible: true, editable: false },
          totalAmount: { visible: true, editable: false },
          paidAmount: { visible: true, editable: false },
          deliveryCharges: { visible: true, editable: false },
          expectedDeliveryDate: { visible: true, editable: false },
          pricingPolicy: { visible: false, editable: false },
          createdDate: { visible: false, editable: false },
          updatedDate: { visible: false, editable: false },
          driver: { visible: false, editable: false },
          vehicleNumber: { visible: false, editable: false },
          images: { visible: false, editable: false },
          addImages: { visible: false, editable: false },
          products: { visible: true, editable: true },
          orderFooter: { visible: true, editable: true },
          stock: { visible: false, editable: false },
          btnSave: { visible: true, editable: true },
          btnCancel: { visible: true, editable: true },
          btnInvoice: { visible: true, editable: true },
          btnInventory: { visible: false, editable: false },
          actionButtons: { visible: false, editable: false },
          btnApprove: { visible: false, editable: false },
          btnReject: { visible: false, editable: false },
        }
      },
      SidebarList: {
        fields: {
          Dashboard: {visible: false, editable: true},
          Customers: {visible: false, editable: true},
          Settings: {visible: false, editable: true}
        }
      },
      catalog: {
        fields: {
          selectBranch: { visible: true, editable: true },
          search: { visible: true, editable: true },
          products: { visible: true, editable: true },
          quantityController: { visible: true, editable: true },
          addToCart: { visible: true, editable: true },
          goToCart: { visible: true, editable: true },
          sort: { visible: true, editable: true }
        }
      },
    },

    [constants.DESIGNATIONS.OPS_COORDINATOR]: {
      // Define opsCordinator permissions for all forms
        orderList: {
        fields: {
          orderNumber: { visible: true, editable: true },
          companyName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          expectedDeliveryDate: { visible: true, editable: true },
          paymentStatus: { visible: true, editable: true },
          totalAmount: { visible: true, editable: true },
          paidAmount: { visible: true, editable: true },
          status: { visible: true, editable: true },
          action: { visible: false, editable: true },
          addButton: { visible: true, editable: true },
          orderBy: { visible: true, editable: true },
        },
      },
      orderDetailAdd: {
        fields: {
          orderDetails: { visible: true, editable: false },
          customerName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          orderBy: { visible: true, editable: true },
          erpId: { visible: true, editable: false },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          totalAmount: { visible: true, editable: false },
          paidAmount: { visible: false, editable: false },
          deliveryCharges: { visible: true, editable: false },
          expectedDeliveryDate: { visible: true, editable: true },
          pricingPolicy: { visible: true, editable: true },
          createdDate: { visible: false, editable: false },
          updatedDate: { visible: false, editable: false },
          driver: { visible: false, editable: false },
          vehicleNumber: { visible: false, editable: false },
          images: { visible: true, editable: true },
          addImages: { visible: false, editable: false },
          products: { visible: true, editable: true },
          orderFooter: { visible: true, editable: true },
          btnSave: { visible: true, editable: true },
          btnCancel: { visible: true, editable: true },
          btnInvoice: { visible: true, editable: true },
          btnPay: { visible: false, editable: false },
          btnInventory: { visible: true, editable: true },
          actionButtons: { visible: true, editable: true },
          btnApprove: { visible: true, editable: true },
          btnReject: { visible: true, editable: true },
        },
      },
      orderDetailEdit: {
        fields: {
          orderDetails: { visible: true, editable: false },
          customerName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          orderBy: { visible: true, editable: true },
          erpId: { visible: true, editable: true },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          totalAmount: { visible: true, editable: true },
          paidAmount: { visible: true, editable: true },
          deliveryCharges: { visible: true, editable: true },
          expectedDeliveryDate: { visible: true, editable: true },
          createdDate: { visible: true, editable: true },
          updatedDate: { visible: true, editable: true },
          driver: { visible: true, editable: true },
          vehicleNumber: { visible: true, editable: true },
          images: { visible: true, editable: true },
          addImages: { visible: true, editable: true },
          products: { visible: true, editable: true },
          orderFooter: { visible: true, editable: true },
          btnSave: { visible: true, editable: true },
          btnCancel: { visible: true, editable: true },
          btnInvoice: { visible: true, editable: true },
          btnInventory: { visible: true, editable: true },
          actionButtons: { visible: true, editable: true },
          btnApprove: { visible: true, editable: true },
          btnReject: { visible: true, editable: true },
        }
      },
      catalog: {
        fields: {
          selectBranch: { visible: false, editable: false },
          search: { visible: true, editable: true },
          products: { visible: true, editable: true },
          quantityController: { visible: false, editable: false },
          addToCart: { visible: false, editable: false },
          goToCart: { visible: false, editable: false },
          sort: { visible: false, editable: false }
        }
      },
      custDetailsAdd: {
        fields: {
          companyNameEn: { visible: true, editable: true },
          companyNameLc: { visible: true, editable: true },
          crNumber: { visible: true, editable: true },
          vatRegistrationNumber: { visible: true, editable: true },
          baladeahLicense: { visible: true, editable: true },
          companyType: { visible: true, editable: true },
          businessType: { visible: true, editable: true },
          businessTypeOther: { visible: true, editable: true },
          interCompany: { visible: true, editable: true },
          entity: { visible: true, editable: true },
          deliveryLocations: { visible: true, editable: true },
          brandName: { visible: true, editable: true },
          brandNameArabic: { visible: true, editable: true },
          company_logo: { visible: true, editable: true },
          brand_logo: { visible: true, editable: true },
          primaryContactName: { visible: true, editable: true },
          primaryContactDesignation: { visible: true, editable: true },
          primaryContactEmail: { visible: true, editable: true },
          primaryContactMobile: { visible: true, editable: true },
          businessHeadSameAsPrimary: { visible: true, editable: true },
          businessHeadName: { visible: true, editable: true },
          businessHeadDesignation: { visible: true, editable: true },
          businessHeadEmail: { visible: true, editable: true },
          businessHeadMobile: { visible: true, editable: true },
          financeHeadName: { visible: true, editable: true },
          financeHeadDesignation: { visible: true, editable: true },
          financeHeadEmail: { visible: true, editable: true },
          financeHeadMobile: { visible: true, editable: true },
          purchasingHeadName: { visible: true, editable: true },
          purchasingHeadDesignation: { visible: true, editable: true },
          purchasingHeadEmail: { visible: true, editable: true },
          purchasingHeadMobile: { visible: true, editable: true },
          buildingName: { visible: true, editable: true },
          street: { visible: true, editable: true },
          district: { visible: true, editable: true },
          city: { visible: true, editable: true },
          region: { visible: true, editable: true },
          zone: { visible: true, editable: true },
          geolocation: { visible: true, editable: true },
          pincode: { visible: true, editable: true },
          dulySigned: { visible: true, editable: true },
          crCertificate: { visible: true, editable: true },
          vatCertificate: { visible: true, editable: true },
          nationalID: { visible: true, editable: true },
          bankLetter: { visible: true, editable: true },
          nonTradingDocuments: { visible: true, editable: true },
          bankName: { visible: true, editable: true },
          accountNumber: { visible: true, editable: true },
          ibanNumber: { visible: true, editable: true },
          prePayment: { visible: true, editable: true },
          partialPayment: { visible: true, editable: true },
          advancePayment: { visible: true, editable: true },
          COD: { visible: true, editable: true },
          credit: { visible: true, editable: true },
          creditLimit: { visible: true, editable: true },
          creditPeriod: { visible: true, editable: true },
          btnSave: { visible: false, editable: true },
          btnSubmit: {visible: false, editable: true},
        },
      },
      custDetailsEdit: {
        fields: {
          companyNameEn: { visible: true, editable: true },
          companyNameLc: { visible: true, editable: true },
          crNumber: { visible: true, editable: true },
          vatRegistrationNumber: { visible: true, editable: true },
          baladeahLicense: { visible: true, editable: true },
          companyType: { visible: true, editable: true },
          businessType: { visible: true, editable: true },
          businessTypeOther: { visible: true, editable: true },
          interCompany: { visible: true, editable: true },
          entity: { visible: true, editable: true },
          deliveryLocations: { visible: true, editable: true },
          brandName: { visible: true, editable: true },
          brandNameArabic: { visible: true, editable: true },
          company_logo: { visible: true, editable: true },
          brand_logo: { visible: true, editable: true },
          primaryContactName: { visible: true, editable: true },
          primaryContactDesignation: { visible: true, editable: true },
          primaryContactEmail: { visible: true, editable: true },
          primaryContactMobile: { visible: true, editable: true },
          businessHeadSameAsPrimary: { visible: true, editable: true },
          businessHeadName: { visible: true, editable: true },
          businessHeadDesignation: { visible: true, editable: true },
          businessHeadEmail: { visible: true, editable: true },
          businessHeadMobile: { visible: true, editable: true },
          financeHeadName: { visible: true, editable: true },
          financeHeadDesignation: { visible: true, editable: true },
          financeHeadEmail: { visible: true, editable: true },
          financeHeadMobile: { visible: true, editable: true },
          purchasingHeadName: { visible: true, editable: true },
          purchasingHeadDesignation: { visible: true, editable: true },
          purchasingHeadEmail: { visible: true, editable: true },
          purchasingHeadMobile: { visible: true, editable: true },
          buildingName: { visible: true, editable: true },
          street: { visible: true, editable: true },
          district: { visible: true, editable: true },
          city: { visible: true, editable: true },
          region: { visible: true, editable: true },
          zone: { visible: true, editable: true },
          geolocation: { visible: true, editable: true },
          pincode: { visible: true, editable: true },
          dulySigned: { visible: true, editable: true },
          crCertificate: { visible: true, editable: true },
          vatCertificate: { visible: true, editable: true },
          nationalID: { visible: true, editable: true },
          bankLetter: { visible: true, editable: true },
          nonTradingDocuments: { visible: true, editable: true },
          bankName: { visible: true, editable: true },
          accountNumber: { visible: true, editable: true },
          ibanNumber: { visible: true, editable: true },
          prePayment: { visible: true, editable: true },
          partialPayment: { visible: true, editable: true },
          advancePayment: { visible: true, editable: true },
          COD: { visible: true, editable: true },
          credit: { visible: true, editable: true },
          creditLimit: { visible: true, editable: true },
          creditPeriod: { visible: true, editable: true },
          btnBlock: {visible: false, editable: true},
          btnUnblock: {visible: false, editable: true},
          assignedTo: {visible: true, editable: true},
          btnSaveChanges: { visible: false, editable: true },
        }
      },
      SidebarList: {
        fields: {
          Dashboard: {visible: false, editable: true},
          Company: {visible: false, editable: true},
          Settings: {visible: false, editable: true}
        }
      }
    },

    [constants.DESIGNATIONS.OPS_MANAGER]: {
      orderList: {
        fields: {
          orderNumber: { visible: true, editable: true },
          companyName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          expectedDeliveryDate: { visible: true, editable: true },
          paymentStatus: { visible: true, editable: true },
          totalAmount: { visible: true, editable: true },
          paidAmount: { visible: true, editable: true },
          status: { visible: true, editable: true },
          action: { visible: false, editable: true },
          addButton: { visible: true, editable: true },
          orderBy: { visible: true, editable: true },
        },
      },
      orderDetailAdd: {
        fields: {
          orderDetails: { visible: true, editable: false },
          customerName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          orderBy: { visible: true, editable: true },
          erpId: { visible: true, editable: false },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          totalAmount: { visible: true, editable: false },
          paidAmount: { visible: false, editable: false },
          deliveryCharges: { visible: true, editable: false },
          expectedDeliveryDate: { visible: true, editable: true },
          pricingPolicy: { visible: true, editable: true },
          createdDate: { visible: false, editable: false },
          updatedDate: { visible: false, editable: false },
          driver: { visible: false, editable: false },
          vehicleNumber: { visible: false, editable: false },
          images: { visible: true, editable: true },
          addImages: { visible: false, editable: false },
          products: { visible: true, editable: true },
          orderFooter: { visible: true, editable: true },
          btnSave: { visible: true, editable: true },
          btnCancel: { visible: true, editable: true },
          btnInvoice: { visible: true, editable: true },
          btnPay: { visible: false, editable: false },
          btnInventory: { visible: true, editable: true },
          actionButtons: { visible: true, editable: true },
          btnApprove: { visible: true, editable: true },
          btnReject: { visible: true, editable: true },
        },
      },
      orderDetailEdit: {
        fields: {
          orderDetails: { visible: true, editable: false },
          customerName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          orderBy: { visible: true, editable: true },
          erpId: { visible: true, editable: true },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          totalAmount: { visible: true, editable: true },
          paidAmount: { visible: true, editable: true },
          deliveryCharges: { visible: true, editable: true },
          expectedDeliveryDate: { visible: true, editable: true },
          createdDate: { visible: true, editable: true },
          updatedDate: { visible: true, editable: true },
          driver: { visible: true, editable: true },
          vehicleNumber: { visible: true, editable: true },
          images: { visible: true, editable: true },
          addImages: { visible: true, editable: true },
          products: { visible: true, editable: true },
          orderFooter: { visible: true, editable: true },
          btnSave: { visible: true, editable: true },
          btnCancel: { visible: true, editable: true },
          btnInvoice: { visible: true, editable: true },
          btnInventory: { visible: true, editable: true },
          actionButtons: { visible: true, editable: true },
          btnApprove: { visible: true, editable: true },
          btnReject: { visible: true, editable: true },
        }
      },
      catalog: {
        fields: {
          selectBranch: { visible: false, editable: false },
          search: { visible: true, editable: true },
          products: { visible: true, editable: true },
          quantityController: { visible: false, editable: false },
          addToCart: { visible: false, editable: false },
          goToCart: { visible: false, editable: false },
          sort: { visible: false, editable: false }
        }
      },
      custDetailsAdd: {
        fields: {
          companyNameEn: { visible: true, editable: true },
          companyNameLc: { visible: true, editable: true },
          crNumber: { visible: true, editable: true },
          vatRegistrationNumber: { visible: true, editable: true },
          baladeahLicense: { visible: true, editable: true },
          companyType: { visible: true, editable: true },
          businessType: { visible: true, editable: true },
          businessTypeOther: { visible: true, editable: true },
          interCompany: { visible: true, editable: true },
          entity: { visible: true, editable: true },
          deliveryLocations: { visible: true, editable: true },
          brandName: { visible: true, editable: true },
          brandNameArabic: { visible: true, editable: true },
          company_logo: { visible: true, editable: true },
          brand_logo: { visible: true, editable: true },
          primaryContactName: { visible: true, editable: true },
          primaryContactDesignation: { visible: true, editable: true },
          primaryContactEmail: { visible: true, editable: true },
          primaryContactMobile: { visible: true, editable: true },
          businessHeadSameAsPrimary: { visible: true, editable: true },
          businessHeadName: { visible: true, editable: true },
          businessHeadDesignation: { visible: true, editable: true },
          businessHeadEmail: { visible: true, editable: true },
          businessHeadMobile: { visible: true, editable: true },
          financeHeadName: { visible: true, editable: true },
          financeHeadDesignation: { visible: true, editable: true },
          financeHeadEmail: { visible: true, editable: true },
          financeHeadMobile: { visible: true, editable: true },
          purchasingHeadName: { visible: true, editable: true },
          purchasingHeadDesignation: { visible: true, editable: true },
          purchasingHeadEmail: { visible: true, editable: true },
          purchasingHeadMobile: { visible: true, editable: true },
          buildingName: { visible: true, editable: true },
          street: { visible: true, editable: true },
          district: { visible: true, editable: true },
          city: { visible: true, editable: true },
          region: { visible: true, editable: true },
          zone: { visible: true, editable: true },
          geolocation: { visible: true, editable: true },
          pincode: { visible: true, editable: true },
          dulySigned: { visible: true, editable: true },
          crCertificate: { visible: true, editable: true },
          vatCertificate: { visible: true, editable: true },
          nationalID: { visible: true, editable: true },
          bankLetter: { visible: true, editable: true },
          nonTradingDocuments: { visible: true, editable: true },
          bankName: { visible: true, editable: true },
          accountNumber: { visible: true, editable: true },
          ibanNumber: { visible: true, editable: true },
          prePayment: { visible: true, editable: true },
          partialPayment: { visible: true, editable: true },
          advancePayment: { visible: true, editable: true },
          COD: { visible: true, editable: true },
          credit: { visible: true, editable: true },
          creditLimit: { visible: true, editable: true },
          creditPeriod: { visible: true, editable: true },
          btnSave: { visible: false, editable: true },
          btnBlock: { visible: true, editable: true},
          btnUnblock: {visible: true, editable: true},
          btnSubmit: {visible: false, editable: true},
        }
      },
      custDetailsEdit: {
        fields: {
          companyNameEn: { visible: true, editable: true },
          companyNameLc: { visible: true, editable: true },
          crNumber: { visible: true, editable: true },
          vatRegistrationNumber: { visible: true, editable: true },
          baladeahLicense: { visible: true, editable: true },
          companyType: { visible: true, editable: true },
          businessType: { visible: true, editable: true },
          businessTypeOther: { visible: true, editable: true },
          interCompany: { visible: true, editable: true },
          entity: { visible: true, editable: true },
          deliveryLocations: { visible: true, editable: true },
          brandName: { visible: true, editable: true },
          brandNameArabic: { visible: true, editable: true },
          company_logo: { visible: true, editable: true },
          brand_logo: { visible: true, editable: true },
          primaryContactName: { visible: true, editable: true },
          primaryContactDesignation: { visible: true, editable: true },
          primaryContactEmail: { visible: true, editable: true },
          primaryContactMobile: { visible: true, editable: true },
          businessHeadSameAsPrimary: { visible: true, editable: true },
          businessHeadName: { visible: true, editable: true },
          businessHeadDesignation: { visible: true, editable: true },
          businessHeadEmail: { visible: true, editable: true },
          businessHeadMobile: { visible: true, editable: true },
          financeHeadName: { visible: true, editable: true },
          financeHeadDesignation: { visible: true, editable: true },
          financeHeadEmail: { visible: true, editable: true },
          financeHeadMobile: { visible: true, editable: true },
          purchasingHeadName: { visible: true, editable: true },
          purchasingHeadDesignation: { visible: true, editable: true },
          purchasingHeadEmail: { visible: true, editable: true },
          purchasingHeadMobile: { visible: true, editable: true },
          buildingName: { visible: true, editable: true },
          street: { visible: true, editable: true },
          district: { visible: true, editable: true },
          city: { visible: true, editable: true },
          region: { visible: true, editable: true },
          zone: { visible: true, editable: true },
          geolocation: { visible: true, editable: true },
          pincode: { visible: true, editable: true },
          dulySigned: { visible: true, editable: true },
          crCertificate: { visible: true, editable: true },
          vatCertificate: { visible: true, editable: true },
          nationalID: { visible: true, editable: true },
          bankLetter: { visible: true, editable: true },
          nonTradingDocuments: { visible: true, editable: true },
          bankName: { visible: true, editable: true },
          accountNumber: { visible: true, editable: true },
          ibanNumber: { visible: true, editable: true },
          prePayment: { visible: true, editable: true },
          partialPayment: { visible: true, editable: true },
          advancePayment: { visible: true, editable: true },
          COD: { visible: true, editable: true },
          credit: { visible: true, editable: true },
          creditLimit: { visible: true, editable: true },
          creditPeriod: { visible: true, editable: true },
          btnBlock: { visible: false, editable: true},
          btnUnblock: {visible: false, editable: true},
          btnSaveChanges: {visible: false, editable: true},
        }
      },
      SidebarList: {
        fields: {
          Dashboard: {visible: false, editable: true},
          Company: {visible: false, editable: true},
          Settings: {visible: false, editable: true}
        }
      }
    },

    [constants.DESIGNATIONS.SALES_EXECUTIVE]: {
      orderList: {
        fields: {
          orderNumber: { visible: true, editable: true },
          companyName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          expectedDeliveryDate: { visible: true, editable: true },
          paymentStatus: { visible: true, editable: true },
          totalAmount: { visible: true, editable: true },
          paidAmount: { visible: true, editable: true },
          status: { visible: true, editable: true },
          action: { visible: false, editable: true },
          addButton: { visible: true, editable: true },
          orderBy: { visible: true, editable: true },
        },
      },
      orderDetailAdd: {
          fields: {
          orderDetails: { visible: true, editable: false },
          customerName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          orderBy: { visible: false, editable: true },
          erpId: { visible: false, editable: false },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          totalAmount: { visible: true, editable: false },
          paidAmount: { visible: false, editable: false },
          deliveryCharges: { visible: true, editable: false },
          expectedDeliveryDate: { visible: true, editable: true },
          pricingPolicy: { visible: true, editable: true },
          createdDate: { visible: false, editable: false },
          updatedDate: { visible: false, editable: false },
          driver: { visible: false, editable: false },
          vehicleNumber: { visible: false, editable: false },
          images: { visible: false, editable: true },
          addImages: { visible: false, editable: false },
          products: { visible: true, editable: true },
          orderFooter: { visible: true, editable: true },
          btnSave: { visible: true, editable: true },
          btnCancel: { visible: true, editable: true },
          btnInvoice: { visible: true, editable: true },
          btnPay: { visible: false, editable: false },
          btnInventory: { visible: true, editable: true },
          actionButtons: { visible: true, editable: true },
          btnApprove: { visible: true, editable: true },
          btnReject: { visible: true, editable: true },
        },
      },
      orderDetailEdit: {
        fields: {
          orderDetails: { visible: true, editable: false },
          customerName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          orderBy: { visible: false, editable: true },
          erpId: { visible: false, editable: false },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          totalAmount: { visible: true, editable: false },
          paidAmount: { visible: false, editable: false },
          deliveryCharges: { visible: true, editable: false },
          expectedDeliveryDate: { visible: true, editable: true },
          pricingPolicy: { visible: true, editable: true },
          createdDate: { visible: false, editable: false },
          updatedDate: { visible: false, editable: false },
          driver: { visible: false, editable: false },
          vehicleNumber: { visible: false, editable: false },
          images: { visible: true, editable: true },
          addImages: { visible: false, editable: false },
          products: { visible: true, editable: true },
          orderFooter: { visible: true, editable: true },
          btnSave: { visible: true, editable: true },
          btnCancel: { visible: true, editable: true },
          btnInvoice: { visible: true, editable: true },
          btnPay: { visible: false, editable: false },
          btnInventory: { visible: true, editable: true },
          actionButtons: { visible: true, editable: true },
          btnApprove: { visible: true, editable: true },
          btnReject: { visible: true, editable: true },
        }
      },
      catalog: {
        fields: {
          selectBranch: { visible: false, editable: false },
          search: { visible: true, editable: true },
          products: { visible: true, editable: true },
          quantityController: { visible: false, editable: false },
          addToCart: { visible: false, editable: false },
          goToCart: { visible: false, editable: false },
          sort: { visible: false, editable: false }
        }
      },
      SidebarList: {
        fields: {
          Dashboard: {visible: false, editable: true},
          Company: {visible: false, editable: true},
          Settings: {visible: false, editable: true}
        }
      }
    },

    [constants.DESIGNATIONS.AREA_SALES_MANAGER]: {
      orderList: {
        fields: {
          orderNumber: { visible: true, editable: true },
          companyName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          expectedDeliveryDate: { visible: true, editable: true },
          paymentStatus: { visible: true, editable: true },
          totalAmount: { visible: true, editable: true },
          paidAmount: { visible: true, editable: true },
          status: { visible: true, editable: true },
          action: { visible: false, editable: true },
          addButton: { visible: true, editable: true },
          orderBy: { visible: true, editable: true },
        },
      },
      orderDetailAdd: {
        fields: {
          orderDetails: { visible: true, editable: false },
          customerName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          orderBy: { visible: true, editable: true },
          erpId: { visible: true, editable: false },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          totalAmount: { visible: true, editable: false },
          paidAmount: { visible: false, editable: false },
          deliveryCharges: { visible: true, editable: false },
          expectedDeliveryDate: { visible: true, editable: true },
          pricingPolicy: { visible: true, editable: true },
          createdDate: { visible: false, editable: false },
          updatedDate: { visible: false, editable: false },
          driver: { visible: false, editable: false },
          vehicleNumber: { visible: false, editable: false },
          images: { visible: false, editable: true },
          addImages: { visible: false, editable: false },
          products: { visible: true, editable: true },
          productIdCol: { visible: true, editable: false },
          quantityCol: { visible: true, editable: false },
          unitCol: { visible: true, editable: false },
          unitPriceCol: { visible: true, editable: false },
          sugarTaxPriceCol: { visible: true, editable: false },
          vatPercentageCol: { visible: true, editable: false },
          netAmountCol: { visible: true, editable: false },
          actionsCol: { visible: true, editable: false },
          deleteButton: { visible: false, editable: false },
          orderFooter: { visible: true, editable: true },
          btnSave: { visible: true, editable: true },
          btnCancel: { visible: true, editable: true },
          btnInvoice: { visible: true, editable: true },
          btnPay: { visible: false, editable: false },
          btnInventory: { visible: true, editable: true },
          actionButtons: { visible: true, editable: true },
          btnApprove: { visible: true, editable: true },
          btnReject: { visible: true, editable: true },
        },
      },
      orderDetailEdit: {
        fields: {
          orderDetails: { visible: true, editable: false },
          customerName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          orderBy: { visible: true, editable: true },
          erpId: { visible: true, editable: true },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          totalAmount: { visible: true, editable: true },
          paidAmount: { visible: true, editable: true },
          deliveryCharges: { visible: true, editable: true },
          expectedDeliveryDate: { visible: true, editable: true },
          createdDate: { visible: true, editable: true },
          updatedDate: { visible: true, editable: true },
          driver: { visible: true, editable: true },
          vehicleNumber: { visible: true, editable: true },
          images: { visible: true, editable: true },
          addImages: { visible: true, editable: true },
          products: { visible: true, editable: true },
          productIdCol: { visible: true, editable: false },
          quantityCol: { visible: true, editable: false },
          unitCol: { visible: true, editable: false },
          unitPriceCol: { visible: true, editable: false },
          sugarTaxPriceCol: { visible: true, editable: false },
          vatPercentageCol: { visible: true, editable: false },
          netAmountCol: { visible: true, editable: false },
          orderFooter: { visible: true, editable: true },
          btnSave: { visible: true, editable: true },
          btnCancel: { visible: true, editable: true },
          btnInvoice: { visible: true, editable: true },
          btnInventory: { visible: true, editable: true },
          actionButtons: { visible: true, editable: true },
          btnApprove: { visible: true, editable: true },
          btnReject: { visible: true, editable: true },
        }
      },
      SidebarList: {
        fields: {
          Dashboard: {visible: false, editable: true},
          Company: {visible: false, editable: true},
          Settings: {visible: false, editable: true}
        }
      },
      catalog: {
        fields: {
          selectBranch: { visible: false, editable: false },
          search: { visible: true, editable: true },
          products: { visible: true, editable: true },
          quantityController: { visible: false, editable: false },
          addToCart: { visible: false, editable: false },
          goToCart: { visible: false, editable: false },
          sort: { visible: false, editable: false }
        }
      },
    },

    [constants.DESIGNATIONS.FIELD_ENGINEER]: {
       orderList: {
        fields: {
          orderNumber: { visible: true, editable: true },
          companyName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          expectedDeliveryDate: { visible: true, editable: true },
          paymentStatus: { visible: true, editable: true },
          totalAmount: { visible: true, editable: true },
          paidAmount: { visible: true, editable: true },
          status: { visible: true, editable: true },
          action: { visible: false, editable: true },
          addButton: { visible: true, editable: true },
          orderBy: { visible: true, editable: true },
        },
      },
      orderDetailAdd: {
        fields: {
          orderDetails: { visible: true, editable: false },
          customerName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          orderBy: { visible: true, editable: true },
          erpId: { visible: true, editable: false },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          totalAmount: { visible: true, editable: false },
          paidAmount: { visible: false, editable: false },
          deliveryCharges: { visible: true, editable: false },
          expectedDeliveryDate: { visible: true, editable: true },
          pricingPolicy: { visible: true, editable: true },
          createdDate: { visible: false, editable: false },
          updatedDate: { visible: false, editable: false },
          driver: { visible: false, editable: false },
          vehicleNumber: { visible: false, editable: false },
          images: { visible: true, editable: true },
          addImages: { visible: false, editable: false },
          products: { visible: true, editable: true },
          orderFooter: { visible: true, editable: true },
          btnSave: { visible: true, editable: true },
          btnCancel: { visible: true, editable: true },
          btnInvoice: { visible: true, editable: true },
          btnPay: { visible: false, editable: false },
          btnInventory: { visible: true, editable: true },
          actionButtons: { visible: true, editable: true },
          btnApprove: { visible: true, editable: true },
          btnReject: { visible: true, editable: true },
        },
      },
      orderDetailEdit: {
        fields: {
          orderDetails: { visible: true, editable: false },
          customerName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          orderBy: { visible: true, editable: true },
          erpId: { visible: true, editable: true },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          totalAmount: { visible: true, editable: true },
          paidAmount: { visible: true, editable: true },
          deliveryCharges: { visible: true, editable: true },
          expectedDeliveryDate: { visible: true, editable: true },
          createdDate: { visible: true, editable: true },
          updatedDate: { visible: true, editable: true },
          driver: { visible: true, editable: true },
          vehicleNumber: { visible: true, editable: true },
          images: { visible: true, editable: true },
          addImages: { visible: true, editable: true },
          products: { visible: true, editable: true },
          orderFooter: { visible: true, editable: true },
          btnSave: { visible: true, editable: true },
          btnCancel: { visible: true, editable: true },
          btnInvoice: { visible: true, editable: true },
          btnInventory: { visible: true, editable: true },
          actionButtons: { visible: true, editable: true },
          btnApprove: { visible: true, editable: true },
          btnReject: { visible: true, editable: true },
        }
      },
      catalog: {
        fields: {
          selectBranch: { visible: false, editable: false },
          search: { visible: true, editable: true },
          products: { visible: true, editable: true },
          quantityController: { visible: false, editable: false },
          addToCart: { visible: false, editable: false },
          goToCart: { visible: false, editable: false },
          sort: { visible: false, editable: false }
        }
      },
      SidebarList: {
        fields: {
          Dashboard: {visible: false, editable: true},
          Company: {visible: false, editable: true},
          Settings: {visible: false, editable: true}
        }
      }
    },

    [constants.DESIGNATIONS.MAINTENANCE_TECHNICIAN]: {
      orderList: {
        fields: {
          orderNumber: { visible: true, editable: true },
          companyName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          expectedDeliveryDate: { visible: true, editable: true },
          paymentStatus: { visible: true, editable: true },
          toyalAmount: { visible: true, editable: true },
          paidAmount: { visible: true, editable: true },
          status: { visible: true, editable: true },
          action: { visible: true, editable: true },
          addButton: { visible: true, editable: true },
          orderBy: { visible: true, editable: true },
        },
      },
      orderDetailAdd: {
        fields: {
          orderDetails: { visible: true, editable: false },
          customerName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          orderBy: { visible: true, editable: true },
          erpId: { visible: true, editable: false },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          totalAmount: { visible: true, editable: true },
          paidAmount: { visible: true, editable: true },
          deliveryCharges: { visible: true, editable: true },
          expectedDeliveryDate: { visible: true, editable: true },
          createdDate: { visible: false, editable: false },
          updatedDate: { visible: false, editable: false },
          driver: { visible: true, editable: true },
          vehicleNumber: { visible: true, editable: true },
          images: { visible: true, editable: true },
          addImages: { visible: false, editable: false },
          products: { visible: true, editable: true },
          orderFooter: { visible: true, editable: true },
          btnSave: { visible: true, editable: true },
          btnCancel: { visible: true, editable: true },
          btnInvoice: { visible: true, editable: true },
          btnInventory: { visible: true, editable: true },
          actionButtons: { visible: true, editable: true },
          btnApprove: { visible: true, editable: true },
          btnReject: { visible: true, editable: true },
        },
      },
      orderDetailEdit: {
        fields: {
          orderDetails: { visible: true, editable: false },
          customerName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          orderBy: { visible: true, editable: true },
          erpId: { visible: true, editable: true },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          totalAmount: { visible: true, editable: true },
          paidAmount: { visible: true, editable: true },
          deliveryCharges: { visible: true, editable: true },
          expectedDeliveryDate: { visible: true, editable: true },
          createdDate: { visible: true, editable: true },
          updatedDate: { visible: true, editable: true },
          driver: { visible: true, editable: true },
          vehicleNumber: { visible: true, editable: true },
          images: { visible: true, editable: true },
          addImages: { visible: true, editable: true },
          products: { visible: true, editable: true },
          orderFooter: { visible: true, editable: true },
          btnSave: { visible: true, editable: true },
          btnCancel: { visible: true, editable: true },
          btnInvoice: { visible: true, editable: true },
          btnInventory: { visible: true, editable: true },
          actionButtons: { visible: true, editable: true },
          btnApprove: { visible: true, editable: true },
          btnReject: { visible: true, editable: true },
        }
      },

       catalog: {
        fields: {
          selectBranch: { visible: false, editable: false },
          search: { visible: true, editable: true },
          products: { visible: true, editable: true },
          quantityController: { visible: false, editable: false },
          addToCart: { visible: false, editable: false },
          goToCart: { visible: false, editable: false },
          sort: { visible: false, editable: false }
        }
      },
      SidebarList: {
        fields: {
          Dashboard: {visible: false, editable: true},
          Company: {visible: false, editable: true},
          Settings: {visible: false, editable: true}
        }
      }
    },

    [constants.DESIGNATIONS.DRIVER]: {
      orderList: {
        fields: {
          orderNumber: { visible: true, editable: true },
          companyName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          expectedDeliveryDate: { visible: true, editable: true },
          paymentStatus: { visible: true, editable: true },
          toyalAmount: { visible: true, editable: true },
          paidAmount: { visible: true, editable: true },
          status: { visible: true, editable: true },
          action: { visible: true, editable: true },
          addButton: { visible: true, editable: true },
          orderBy: { visible: true, editable: true },
        },
      },
      orderDetailAdd: {
        fields: {
          orderDetails: { visible: true, editable: false },
          customerName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          orderBy: { visible: true, editable: true },
          erpId: { visible: true, editable: false },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          totalAmount: { visible: true, editable: true },
          paidAmount: { visible: true, editable: true },
          deliveryCharges: { visible: true, editable: true },
          expectedDeliveryDate: { visible: true, editable: true },
          createdDate: { visible: false, editable: false },
          updatedDate: { visible: false, editable: false },
          driver: { visible: true, editable: true },
          vehicleNumber: { visible: true, editable: true },
          images: { visible: true, editable: true },
          addImages: { visible: false, editable: false },
          products: { visible: true, editable: true },
          orderFooter: { visible: true, editable: true },
          btnSave: { visible: true, editable: true },
          btnCancel: { visible: true, editable: true },
          btnInvoice: { visible: true, editable: true },
          btnInventory: { visible: true, editable: true },
          actionButtons: { visible: true, editable: true },
          btnApprove: { visible: true, editable: true },
          btnReject: { visible: true, editable: true },
        },
      },
      orderDetailEdit: {
        fields: {
          orderDetails: { visible: true, editable: false },
          customerName: { visible: true, editable: true },
          branchName: { visible: true, editable: true },
          orderBy: { visible: true, editable: true },
          erpId: { visible: true, editable: true },
          entity: { visible: true, editable: true },
          paymentMethod: { visible: true, editable: true },
          totalAmount: { visible: true, editable: true },
          paidAmount: { visible: true, editable: true },
          deliveryCharges: { visible: true, editable: true },
          expectedDeliveryDate: { visible: true, editable: true },
          createdDate: { visible: true, editable: true },
          updatedDate: { visible: true, editable: true },
          driver: { visible: true, editable: true },
          vehicleNumber: { visible: true, editable: true },
          images: { visible: true, editable: true },
          addImages: { visible: true, editable: true },
          products: { visible: true, editable: true },
          orderFooter: { visible: true, editable: true },
          btnSave: { visible: true, editable: true },
          btnCancel: { visible: true, editable: true },
          btnInvoice: { visible: true, editable: true },
          btnInventory: { visible: true, editable: true },
          actionButtons: { visible: true, editable: true },
          btnApprove: { visible: true, editable: true },
          btnReject: { visible: true, editable: true }
        }
      },
      catalog: {
        fields: {
          selectBranch: { visible: false, editable: false },
          search: { visible: true, editable: true },
          products: { visible: true, editable: true },
          quantityController: { visible: false, editable: false },
          addToCart: { visible: false, editable: false },
          goToCart: { visible: false, editable: false },
          sort: { visible: false, editable: false }
        }
      },
    }
  };

  static getRoles() {
    return Object.keys(RbacManager.roleformfieldmap);
  }

  static getForms(role) {
    return Object.keys(RbacManager.roleformfieldmap?.["admin"] || {});
  }

  getFieldPermissions(role, form) {
    return RbacManager.roleformfieldmap?.[role]?.[form]?.fields || {};
  }

  /**
   * Returns the access definition object for a given field.
   * @param {string} field - The field name (e.g., 'orderNumber', 'customer')
   * @returns {object|undefined} The access definition object or undefined if not found
   */
  getFieldAccess(field) {
    return RbacManager.roleformfieldmap?.[this.currentRole]?.[this.currentForm]?.fields?.[field];
  }

  /**
   * Checks if a field is visible for the current role and form
   * @param {string} field - The field name
   * @returns {boolean} True if the field is visible, false otherwise
   */
  isV(field) {
    //console.log(field)
    const access = this.getFieldAccess(field);
    return access == null ? true : access.visible;
  }

  /**
   * Checks if a field is editable for the current role and form
   * @param {string} field - The field name
   * @returns {boolean} True if the field is editable, false otherwise
   */
  // isE(field, approvalWF = false, fieldInWF = false) {
  //   //console.log(`~~~~~~~~*********Checking access for field: ${field} in form: ${this.currentForm} for role: ${this.currentRole}`);
  //   const access = this.getFieldAccess(field);
  //   //console.log(`~~~~~~~~*********Access for field: ${field} is ${JSON.stringify(access)}`);
  //   {console.log(access == null ? true : access.editable) && (this.itemInWF == null ? true : this.isUserOwner) && ((approvalWF == true && fieldInWF == true) ? true : (approvalWF == true && fieldInWF == false) ? false : true);}
  //   return (access == null ? true : access.editable) && (this.itemInWF == null ? true : this.isUserOwner) && ((approvalWF == true && fieldInWF == true) ? true : (approvalWF == true && fieldInWF == false) ? false : true);
  // }
  isE(field, approvalWF = false, fieldInWF = false) {
    const access = this.getFieldAccess(field);
    //console.log(`~~~~~~~~*********Access for field: ${field} is ${JSON.stringify(access)}`);
    return (
      (access == null ? true : access.editable) &&
      (this.itemInWF == null ? true : this.isUserOwner) &&
      (approvalWF == true && fieldInWF == true ? true : approvalWF == true && fieldInWF == false ? false : true)
    );
  }
}

// Example usage
// const rbacMgr = new RbacManager('admin', 'orderList');
// const isV = rbacMgr.isV.bind(rbacMgr);
// const isE = rbacMgr.isE.bind(rbacMgr);
// console.log(isV('orderNumber')); // true
// console.log(isE('orderNumber')); // true
// console.log(isV('customer')); // false
// console.log(isE('customer')); // true
// console.log(isV('date')); // true
// console.log(isE('date')); // false

export default RbacManager;
